### ISSUE TITLE
Abandoned_carts: When does the warning for max_delete_batch_limit occur?

### ISSUE THREAD

**Issue by DavidNitro** [Nitrokey/odoo-modules#11]
In your package "sale_order.py" line 79-82 is this codechunk:

`def action_remove_sale_order(self):
        max_delete_batch_limit = safe_eval(self.env['ir.config_parameter'].get_param('abandoned_carts.max_delete_batch_limit', '2000'))
        if len(self.sale_order_ids)>max_delete_batch_limit:
            raise Warning('For safety reasons, you cannot delete more than %d sale orders together. You can re-open the wizard several times if needed.'%(max_delete_batch_limit))`

What exactly does this mean? I thought, that this will raise a warning when i type in settings more than 2000 orders to delete at one time. But when i type in "2005" orders to delete, it deletes "2005" orders without any problem.

**Comment by nikunjantala** [comment]
That warning is raise if user will add record manually. Right now I already setup popup to not able to add new record, so that warning never happen.  Whatever Maximum value you will set in Settings and user try to add more records, than it will raise warning. For example, you setup 2500 maximum limit in Settings and than user trying to remove 2550 records at a time, than it will show that error.

**Comment by jans23** [comment]
Why is the "2000" hardcoded in the code? Shouldn't it be checked against whatever value is configured instead?

**Comment by nikunjantala** [comment]
If there is no value given in the configurations, system takes default value as 2000. If it is configured, than that configured value is taken. For example, if user configured value 500, than that value is checked against warning.

**Comment by nikunjantala** [comment]
You get the given example ?

**Comment by DavidNitro** [comment]
Yes. Thank you very much.
